export { CONTACT_QUERY } from "./Contact.query";
export { FACTS_STATS_QUERY } from "./FactsStats.query";
export { GLOBALS_QUERY } from "./Globals.query";
export { HOME_QUERY } from "./Home.query";
export { INTERNSHIPS_VOLUNTEER_QUERY } from "./InternshipsVolunteer.query";
export { JOIN_QUERY } from "./Join.query";
export { MISSION_VISION_QUERY } from "./MissionVision.query";
export { NEWS_STORIES_QUERY } from "./NewsStories.query";
export { PEOPLE_SLUGS_QUERY } from "./People.query";
export { PERSON_QUERY } from "./Person.query";
export { POST_QUERY } from "./Post.query";
export { POSTS_QUERY, POSTS_SLUGS_QUERY } from "./Posts.query";
export { SERVICE_QUERY } from "./Service.query";
export { SERVICES_SLUGS_QUERY } from "./Services.query";
export { TEAM_QUERY } from "./Team.query";
